version: 0.2

phases:
  build:
    commands:
      - echo "Starting deployment..."
      - aws s3 sync . s3://my-cicd-website-2026 --delete --exclude "buildspec.yml" --exclude ".git/*"
      - echo "Deployment complete!"